# Generated by Django 5.2.17 on 2026-08-10 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("category", models.CharField(db_index=True, max_length=32)),
                ("icon", models.CharField(blank=True, max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "db_table": "feature",
                "ordering": ("sort_order", "slug"),
            },
        ),
        migrations.CreateModel(
            name="FeaturePlatformAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("bale", "Bale")],
                        max_length=16,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "degradation_note",
                    models.CharField(
                        blank=True,
                        help_text="Shown in the builder when the feature works, but differently.",
                        max_length=255,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_availability",
                        to="features.feature",
                    ),
                ),
            ],
            options={
                "db_table": "feature_platform_availability",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feature", "platform"), name="feature_platform_uniq"
                    )
                ],
            },
        ),
    ]
