# Generated by Django 5.2.17 on 2026-08-14 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bot_runtime", "0002_initial"),
        ("bots", "0001_initial"),
        ("customers", "0002_tenantinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("message_received", "Message received"),
                            ("command_used", "Command used"),
                            ("route_used", "Menu/route used"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=64)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="bots.bot",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bot_runtime.businesscontact",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_event",
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(
                        fields=["bot", "-occurred_at"], name="analytics_bot_time_idx"
                    )
                ],
            },
        ),
    ]
