# Generated by Django 5.2.17 on 2026-08-10 14:14

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("currency", apps.core.models.CurrencyCodeField(max_length=8)),
                (
                    "country_scope",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ISO country codes this list applies to. Empty means any country.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Used when no list matches the customer's country.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "price_list",
                "ordering": ("currency", "slug"),
            },
        ),
        migrations.CreateModel(
            name="PriceVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price_key",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. feature.appointment.setup, platform.telegram.base",
                        max_length=128,
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                (
                    "billing_kind",
                    models.CharField(
                        choices=[
                            ("ONE_TIME", "One-time"),
                            ("RECURRING_MONTHLY", "Monthly"),
                        ],
                        default="ONE_TIME",
                        max_length=32,
                    ),
                ),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="Null means this is the live price.",
                        null=True,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="pricing.pricelist",
                    ),
                ),
            ],
            options={
                "db_table": "price_version",
                "ordering": ("price_key", "-valid_from"),
                "indexes": [
                    models.Index(
                        fields=["price_list", "price_key"], name="price_lookup_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("valid_to__isnull", True)),
                        fields=("price_list", "price_key"),
                        name="one_live_price_per_key",
                    )
                ],
            },
        ),
    ]
