# Generated by Django 5.2.17 on 2026-08-14 22:47

import apps.core.models
import django.db.models.deletion
import uuid
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bot_runtime", "0002_initial"),
        ("bots", "0001_initial"),
        ("customers", "0002_tenantinvitation"),
    ]

    operations = [
        # Docker's init script (docker/postgres/init-extensions.sql) already creates
        # this in the main dev database, but that script runs once, against one
        # database, at container init — it never touches a freshly created database
        # such as pytest's `test_botbuilder` or a CI run's own database. `IF NOT
        # EXISTS` under the hood makes this a safe no-op wherever it already exists.
        BtreeGistExtension(),
        migrations.CreateModel(
            name="AppointmentService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveSmallIntegerField()),
                ("buffer_minutes", models.PositiveSmallIntegerField(default=0)),
                ("price_minor", models.BigIntegerField(default=0)),
                (
                    "currency",
                    apps.core.models.CurrencyCodeField(blank=True, max_length=8),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_services",
                        to="bots.bot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "appointment_service",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="bots.bot",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        related_name="staff",
                        to="appointments.appointmentservice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "staff_member",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("business_timezone", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("NO_SHOW", "No-show"),
                        ],
                        default="CONFIRMED",
                        max_length=16,
                    ),
                ),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=255)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="bots.bot",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="bot_runtime.businesscontact",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="appointments.appointmentservice",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="appointments.staffmember",
                    ),
                ),
            ],
            options={
                "db_table": "appointment",
                "ordering": ("starts_at",),
            },
        ),
        migrations.CreateModel(
            name="TimeOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_off",
                        to="bots.bot",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_off",
                        to="appointments.staffmember",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "time_off",
                "ordering": ("starts_at",),
            },
        ),
        migrations.AddIndex(
            model_name="appointmentservice",
            index=models.Index(
                fields=["bot", "is_active"], name="appt_service_bot_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["bot", "starts_at"], name="appointment_bot_starts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["staff", "starts_at"], name="appointment_staff_starts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeoff",
            index=models.Index(
                fields=["bot", "starts_at", "ends_at"], name="time_off_bot_range_idx"
            ),
        ),
        # Double-booking is prevented by PostgreSQL, not application logic (DATABASE.md
        # §9): no staff member can hold two overlapping active appointments, full stop,
        # even under a race the availability check in `services.py` cannot see coming.
        # Written as raw SQL rather than Django's `ExclusionConstraint` because that API
        # wants a stored range column; `tstzrange()` computed inline over the two existing
        # datetime columns needs no such column, and duplicating `starts_at`/`ends_at`
        # into one purely to satisfy the ORM would be schema churn for no benefit.
        # `btree_gist` (enabled in Phase 1's init script) is what makes a GiST index
        # accept the plain integer equality on `staff_id`.
        migrations.RunSQL(
            sql="""
                ALTER TABLE appointment
                ADD CONSTRAINT appointment_no_overlap
                EXCLUDE USING gist (
                    staff_id WITH =,
                    tstzrange(starts_at, ends_at, '[)') WITH &&
                )
                WHERE (status = 'CONFIRMED');
            """,
            reverse_sql="ALTER TABLE appointment DROP CONSTRAINT appointment_no_overlap;",
        ),
    ]
