# Generated by Django 5.2.17 on 2026-08-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('task_id', models.CharField(blank=True, max_length=64)),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('exception_type', models.CharField(blank=True, max_length=255)),
                ('exception_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'failed_task_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['task_name', 'created_at'], name='failedtask_name_time_idx')],
            },
        ),
    ]
