"""Business content the bot serves (DATABASE.md §8b).

Entered once by the customer and shared by every channel, so a clinic on Telegram and
Bale has one set of opening hours rather than two that can disagree (spec §3).
"""

from __future__ import annotations

from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.core.models import TenantOwnedModel


class BusinessProfile(TenantOwnedModel):
    bot = models.OneToOneField(
        "bots.Bot", on_delete=models.CASCADE, related_name="business_profile"
    )

    legal_name = models.CharField(max_length=255, blank=True)
    display_name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    logo_file_key = models.CharField(max_length=255, blank=True)

    phone = models.CharField(max_length=32, blank=True)
    secondary_phone = models.CharField(max_length=32, blank=True)
    email = models.EmailField(blank=True)
    website = models.URLField(blank=True)

    address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=128, blank=True)
    country = models.CharField(max_length=2, blank=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    map_url = models.URLField(blank=True)

    timezone = models.CharField(max_length=64, default="UTC")
    socials = models.JSONField(default=dict, blank=True)

    #: Free-text hours, shown verbatim by the `business:hours` handler. Structured
    #: per-weekday rows (see `WorkingHours` below) arrive with the appointment module
    #: in Phase 7, where slot computation actually needs them; until then this is what
    #: both the builder and the dashboard edit.
    working_hours_text = models.CharField(max_length=255, blank=True)

    class Meta:
        db_table = "business_profile"

    def __str__(self) -> str:
        return self.display_name


class WorkingHours(TenantOwnedModel):
    """Weekly schedule. Several rows per weekday support split shifts."""

    bot = models.ForeignKey("bots.Bot", on_delete=models.CASCADE, related_name="working_hours")
    weekday = models.PositiveSmallIntegerField(help_text=_("0 = Monday"))
    opens_at = models.TimeField(null=True, blank=True)
    closes_at = models.TimeField(null=True, blank=True)
    is_closed = models.BooleanField(default=False)

    class Meta:
        db_table = "working_hours"
        ordering = ("weekday", "opens_at")

    def __str__(self) -> str:
        if self.is_closed:
            return f"day {self.weekday}: closed"
        return f"day {self.weekday}: {self.opens_at}–{self.closes_at}"


class FaqEntry(TenantOwnedModel):
    class Source(models.TextChoices):
        MANUAL = "MANUAL", _("Written by the customer")
        AI_GENERATED = "AI_GENERATED", _("Generated by AI")

    bot = models.ForeignKey("bots.Bot", on_delete=models.CASCADE, related_name="faq_entries")
    question = models.CharField(max_length=255)
    answer = models.TextField()
    category = models.CharField(max_length=64, blank=True)
    sort_order = models.PositiveSmallIntegerField(default=100)
    is_active = models.BooleanField(default=True)
    source = models.CharField(max_length=16, choices=Source.choices, default=Source.MANUAL)

    class Meta:
        db_table = "faq_entry"
        ordering = ("sort_order", "id")
        indexes = [
            models.Index(fields=["bot", "is_active", "sort_order"], name="faq_bot_active_idx")
        ]

    def __str__(self) -> str:
        return self.question
