# Generated by Django 5.2.17 on 2026-08-10 14:14

import apps.core.models
import apps.orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business_templates", "0001_initial"),
        ("customers", "0001_initial"),
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "session_secret",
                    models.CharField(
                        default=apps.orders.models._session_secret,
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("WEB", "Website"),
                            ("TELEGRAM_BUILDER", "Telegram builder bot"),
                            ("BALE_BUILDER", "Bale builder bot"),
                        ],
                        default="WEB",
                        max_length=32,
                    ),
                ),
                ("platforms", models.JSONField(default=list)),
                (
                    "selected_features",
                    models.JSONField(
                        default=list,
                        help_text="Feature slugs the customer chose, before dependency expansion.",
                    ),
                ),
                (
                    "resolved_features",
                    models.JSONField(
                        default=list,
                        help_text="What is actually priced, after dependencies and always-on.",
                    ),
                ),
                (
                    "business_draft",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Business details entered in the builder.",
                    ),
                ),
                ("locale", models.CharField(default="en", max_length=8)),
                ("currency", apps.core.models.CurrencyCodeField(max_length=8)),
                ("subtotal_once_minor", models.BigIntegerField(default=0)),
                ("subtotal_recurring_minor", models.BigIntegerField(default=0)),
                ("discount_minor", models.BigIntegerField(default=0)),
                ("tax_minor", models.BigIntegerField(default=0)),
                ("total_minor", models.BigIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("converted_order_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="pricing.pricelist",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="business_templates.businesstemplate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "quote",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price_key", models.CharField(max_length=128)),
                ("label_key", models.CharField(max_length=128)),
                ("feature_slug", models.CharField(blank=True, max_length=64)),
                ("unit_amount_minor", models.BigIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", apps.core.models.CurrencyCodeField(max_length=8)),
                ("billing_kind", models.CharField(max_length=32)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "price_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_items",
                        to="pricing.priceversion",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.quote",
                    ),
                ),
            ],
            options={
                "db_table": "quote_item",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["tenant", "-created_at"], name="quote_tenant_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["expires_at"], name="quote_expiry_idx"),
        ),
    ]
