# Generated by Django 5.2.17 on 2026-08-10 23:32

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_templates", "0001_initial"),
        ("customers", "0001_initial"),
        ("orders", "0001_initial"),
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("number", models.BigIntegerField(editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("PENDING_PAYMENT", "PENDING_PAYMENT"),
                            ("RECEIPT_SUBMITTED", "RECEIPT_SUBMITTED"),
                            ("PAYMENT_REVIEW", "PAYMENT_REVIEW"),
                            ("PAYMENT_REJECTED", "PAYMENT_REJECTED"),
                            ("PAID", "PAID"),
                            ("PROVISIONING", "PROVISIONING"),
                            ("CONFIGURING", "CONFIGURING"),
                            ("DEPLOYING", "DEPLOYING"),
                            ("ACTIVE", "ACTIVE"),
                            ("SUSPENDED", "SUSPENDED"),
                            ("CANCELLED", "CANCELLED"),
                            ("FAILED", "FAILED"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("platforms", models.JSONField(default=list)),
                ("features", models.JSONField(default=list)),
                ("business_snapshot", models.JSONField(blank=True, default=dict)),
                ("locale", models.CharField(default="en", max_length=8)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("WEB", "Website"),
                            ("TELEGRAM_BUILDER", "Telegram builder bot"),
                            ("BALE_BUILDER", "Bale builder bot"),
                        ],
                        default="WEB",
                        max_length=32,
                    ),
                ),
                ("currency", apps.core.models.CurrencyCodeField(max_length=8)),
                ("subtotal_once_minor", models.BigIntegerField(default=0)),
                ("subtotal_recurring_minor", models.BigIntegerField(default=0)),
                ("discount_minor", models.BigIntegerField(default=0)),
                ("discount_reason", models.CharField(blank=True, max_length=255)),
                ("tax_minor", models.BigIntegerField(default=0)),
                ("total_minor", models.BigIntegerField(default=0)),
                ("placed_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "placed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="orders.quote",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="business_templates.businesstemplate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "order",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=32)),
                ("to_status", models.CharField(max_length=32)),
                ("actor_type", models.CharField(default="SYSTEM", max_length=16)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_event",
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price_key", models.CharField(max_length=128)),
                ("label_key", models.CharField(max_length=128)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("feature_slug", models.CharField(blank=True, max_length=64)),
                ("unit_amount_minor", models.BigIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", apps.core.models.CurrencyCodeField(max_length=8)),
                ("billing_kind", models.CharField(max_length=32)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "price_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="pricing.priceversion",
                    ),
                ),
            ],
            options={
                "db_table": "order_item",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "status"], name="order_tenant_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="order_status_time_idx"
            ),
        ),
    ]
