# Generated by Django 5.2.17 on 2026-08-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_number_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="provisioning_strategy",
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
