# Generated by Django 5.2.17 on 2026-08-14 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0001_initial"),
        ("orders", "0004_order_provisioning_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="kind",
            field=models.CharField(
                choices=[
                    ("NEW", "New bot"),
                    ("ADDON", "Add features to an existing bot"),
                ],
                default="NEW",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="target_bot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addon_orders",
                to="bots.bot",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="target_bot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addon_quotes",
                to="bots.bot",
            ),
        ),
    ]
