# Generated by Django 5.2.17 on 2026-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_kind_order_target_bot_quote_target_bot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("PENDING_PAYMENT", "PENDING_PAYMENT"),
                    ("RECEIPT_SUBMITTED", "RECEIPT_SUBMITTED"),
                    ("PAYMENT_REVIEW", "PAYMENT_REVIEW"),
                    ("PAYMENT_REJECTED", "PAYMENT_REJECTED"),
                    ("PAID", "PAID"),
                    ("PROVISIONING", "PROVISIONING"),
                    ("CONFIGURING", "CONFIGURING"),
                    ("DEPLOYING", "DEPLOYING"),
                    ("ACTIVE", "ACTIVE"),
                    ("GRACE_PERIOD", "GRACE_PERIOD"),
                    ("SUSPENDED", "SUSPENDED"),
                    ("CANCELLED", "CANCELLED"),
                    ("FAILED", "FAILED"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=32,
            ),
        ),
    ]
