# Generated by Django 5.2.17 on 2026-08-15 20:17

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bot_runtime", "0002_initial"),
        ("bots", "0001_initial"),
        ("customers", "0002_tenantinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Docker's init script (docker/postgres/init-extensions.sql) already creates this
        # in the main dev database, but that script runs once, against one database, at
        # container init — it never touches a freshly created database such as pytest's
        # `test_botbuilder` or a CI run's own database. `CreateExtension` under the hood is
        # `CREATE EXTENSION IF NOT EXISTS`, so this is a safe no-op wherever it already
        # exists (same reasoning as `BtreeGistExtension()` in appointments' 0001_initial).
        VectorExtension(),
        migrations.CreateModel(
            name="AiConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custom_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Extra rules the assistant must follow, e.g. tone, things never to promise.",
                    ),
                ),
                (
                    "monthly_token_budget",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "bot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_configuration",
                        to="bots.bot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_configuration",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_documents",
                        to="bots.bot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_knowledge_document",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AiUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model", models.CharField(blank=True, max_length=64)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("used_knowledge_base", models.BooleanField(default=False)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_records",
                        to="bots.bot",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bot_runtime.businesscontact",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_usage_record",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["bot", "-created_at"], name="ai_usage_bot_created_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=256)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_chunks",
                        to="bots.bot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="ai.knowledgedocument",
                    ),
                ),
            ],
            options={
                "db_table": "ai_knowledge_chunk",
                "ordering": ("document_id", "position"),
                "indexes": [
                    models.Index(
                        fields=["bot", "document"], name="ai_chunk_bot_document_idx"
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="ai_chunk_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
            },
        ),
    ]
