# Generated by Django 5.2.17 on 2026-08-11 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("bale", "Bale")],
                        max_length=16,
                    ),
                ),
                ("chat_ref", models.CharField(max_length=64)),
                ("user_ref", models.CharField(max_length=64)),
                ("state", models.CharField(default="IDLE", max_length=64)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("locale", models.CharField(blank=True, max_length=8)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "bot_session",
            },
        ),
        migrations.CreateModel(
            name="BusinessContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("bale", "Bale")],
                        max_length=16,
                    ),
                ),
                ("platform_user_id", models.CharField(max_length=64)),
                ("display_name", models.CharField(blank=True, max_length=128)),
                ("username", models.CharField(blank=True, max_length=64)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("locale", models.CharField(blank=True, max_length=8)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="The user blocked the bot, or the chat is gone.",
                    ),
                ),
            ],
            options={
                "db_table": "business_contact",
            },
        ),
        migrations.CreateModel(
            name="InboundUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_update_id", models.BigIntegerField()),
                ("raw", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                            ("IGNORED", "Ignored"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "db_table": "inbound_update",
            },
        ),
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chat_ref", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("DROPPED", "Dropped"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("platform_message_id", models.CharField(blank=True, max_length=64)),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_bulk", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "outbound_message",
                "ordering": ("created_at",),
            },
        ),
    ]
