# Generated by Django 5.2.17 on 2026-08-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bot_runtime", "0001_initial"),
        ("bots", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botsession",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="bots.bot",
            ),
        ),
        migrations.AddField(
            model_name="businesscontact",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="bots.bot",
            ),
        ),
        migrations.AddField(
            model_name="businesscontact",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="customers.tenant",
            ),
        ),
        migrations.AddField(
            model_name="inboundupdate",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inbound_updates",
                to="bots.botplatforminstance",
            ),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outbound_messages",
                to="bots.botplatforminstance",
            ),
        ),
        migrations.AddConstraint(
            model_name="botsession",
            constraint=models.UniqueConstraint(
                fields=("bot", "platform", "chat_ref", "user_ref"),
                name="bot_session_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="businesscontact",
            index=models.Index(
                fields=["tenant", "-last_seen_at"], name="contact_tenant_seen_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="businesscontact",
            constraint=models.UniqueConstraint(
                fields=("bot", "platform", "platform_user_id"),
                name="business_contact_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="inboundupdate",
            index=models.Index(
                fields=["status", "received_at"], name="inbound_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundupdate",
            constraint=models.UniqueConstraint(
                fields=("instance", "platform_update_id"), name="inbound_update_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="outboundmessage",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="outbound_retry_idx"
            ),
        ),
    ]
