# Generated by Django 5.1.15 on 2026-08-10 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('STAFF', 'Staff'), ('SYSTEM', 'System'), ('ANONYMOUS', 'Anonymous')], default='SYSTEM', max_length=16)),
                ('actor_label', models.CharField(blank=True, help_text='Preserved even if the account is deleted.', max_length=255)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('request_id', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.tenant')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='audit_tenant_time_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_resource_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_time_idx')],
            },
        ),
    ]
