# Generated by Django 5.2.17 on 2026-08-16 10:34

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0001_initial"),
        ("customers", "0002_tenantinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("GRACE_PERIOD", "Grace period"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("monthly_amount_minor", models.BigIntegerField(default=0)),
                ("currency", apps.core.models.CurrencyCodeField(max_length=8)),
                ("current_period_end", models.DateTimeField()),
                ("grace_period_ends_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_reminder_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "bot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="bots.bot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "subscription",
                "indexes": [
                    models.Index(
                        fields=["status", "current_period_end"],
                        name="subscription_active_sweep_idx",
                    ),
                    models.Index(
                        fields=["status", "grace_period_ends_at"],
                        name="subscription_grace_sweep_idx",
                    ),
                ],
            },
        ),
    ]
