# Generated by Django 5.2.17 on 2026-08-11 10:31

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business_templates", "0001_initial"),
        ("customers", "0001_initial"),
        ("features", "0001_initial"),
        ("orders", "0004_order_provisioning_strategy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROVISIONING", "Provisioning"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("FAILED", "Failed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("default_locale", models.CharField(default="en", max_length=8)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "currency",
                    apps.core.models.CurrencyCodeField(default="USD", max_length=8),
                ),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "origin_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bots",
                        to="orders.order",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bots",
                        to="business_templates.businesstemplate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "bot",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BotConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("welcome_message", models.TextField(blank=True)),
                ("menu", models.JSONField(blank=True, default=list)),
                ("branding", models.JSONField(blank=True, default=dict)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "bot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "db_table": "bot_configuration",
            },
        ),
        migrations.CreateModel(
            name="BotFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_features",
                        to="bots.bot",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bot_features",
                        to="features.feature",
                    ),
                ),
                (
                    "source_order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "db_table": "bot_feature",
            },
        ),
        migrations.CreateModel(
            name="BotPlatformInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("bale", "Bale")],
                        max_length=16,
                    ),
                ),
                ("platform_bot_id", models.CharField(blank=True, max_length=64)),
                ("username", models.CharField(blank=True, max_length=64)),
                ("display_name", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("AWAITING_TOKEN", "Waiting for the customer's token"),
                            ("CONFIGURING", "Configuring"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                (
                    "acquisition_mode",
                    models.CharField(
                        choices=[
                            ("POOL", "Assigned from the platform pool"),
                            ("TOKEN_HANDOFF", "Customer supplied the token"),
                            ("MTPROTO", "Created by the operations tool"),
                        ],
                        max_length=24,
                    ),
                ),
                ("webhook_url", models.URLField(blank=True)),
                ("webhook_set_at", models.DateTimeField(blank=True, null=True)),
                ("last_update_at", models.DateTimeField(blank=True, null=True)),
                ("last_send_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "db_table": "bot_platform_instance",
            },
        ),
        migrations.CreateModel(
            name="BotCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ciphertext", models.BinaryField()),
                ("kek_version", models.PositiveSmallIntegerField(default=1)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential",
                        to="bots.botplatforminstance",
                    ),
                ),
            ],
            options={
                "db_table": "bot_credential",
            },
        ),
        migrations.CreateModel(
            name="BotPoolEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("bale", "Bale")],
                        max_length=16,
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                ("platform_bot_id", models.CharField(blank=True, max_length=64)),
                ("ciphertext", models.BinaryField()),
                ("kek_version", models.PositiveSmallIntegerField(default=1)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("ASSIGNED", "Assigned"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=16,
                    ),
                ),
                ("reserved_until", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "assigned_instance",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pool_entry",
                        to="bots.botplatforminstance",
                    ),
                ),
            ],
            options={
                "db_table": "bot_pool_entry",
                "ordering": ("platform", "username"),
            },
        ),
        migrations.CreateModel(
            name="WebhookSecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("secret_hash", models.CharField(db_index=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_secrets",
                        to="bots.botplatforminstance",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_secret",
                "ordering": ("-valid_from",),
            },
        ),
        migrations.AddIndex(
            model_name="bot",
            index=models.Index(
                fields=["tenant", "status"], name="bot_tenant_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="botfeature",
            constraint=models.UniqueConstraint(
                fields=("bot", "feature"), name="bot_feature_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="botplatforminstance",
            constraint=models.UniqueConstraint(
                fields=("bot", "platform"), name="bot_platform_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="botplatforminstance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("platform_bot_id", ""), _negated=True),
                fields=("platform", "platform_bot_id"),
                name="platform_bot_id_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="botpoolentry",
            index=models.Index(
                fields=["platform", "status"], name="pool_platform_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="botpoolentry",
            constraint=models.UniqueConstraint(
                fields=("platform", "username"), name="pool_platform_username_uniq"
            ),
        ),
    ]
