# Generated by Django 5.2.17 on 2026-08-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputRestrictionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allowed_calling_codes", models.JSONField(blank=True, default=list)),
                ("blocked_phone_numbers", models.JSONField(blank=True, default=list)),
                ("collect_email_on_consultation", models.BooleanField(default=False)),
                ("allowed_email_domains", models.JSONField(blank=True, default=list)),
                ("blocked_email_domains", models.JSONField(blank=True, default=list)),
                ("strict_email_format", models.BooleanField(default=True)),
                (
                    "bot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_restrictions",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "db_table": "input_restriction_policy",
            },
        ),
    ]
