# Generated by Django 5.2.17 on 2026-08-17 23:30

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0001_initial"),
        ("commerce", "0001_initial"),
        ("customers", "0002_tenantinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to="public/products/%Y/%m/"
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="commerce.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_image",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="PropertyListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("SALE", "For sale"), ("RENT", "For rent")],
                        max_length=16,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Apartment"),
                            ("HOUSE", "House"),
                            ("LAND", "Land"),
                            ("COMMERCIAL", "Commercial"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bathrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("area_sqm", models.PositiveIntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("price_minor", models.BigIntegerField()),
                ("currency", apps.core.models.CurrencyCodeField(max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_listings",
                        to="bots.bot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "property_listing",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to="public/properties/%Y/%m/"
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="commerce.propertylisting",
                    ),
                ),
            ],
            options={
                "db_table": "property_image",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("instructor_name", models.CharField(blank=True, max_length=128)),
                ("price_minor", models.BigIntegerField()),
                ("currency", apps.core.models.CurrencyCodeField(max_length=8)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("duration_label", models.CharField(blank=True, max_length=64)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("enrolled_count", models.PositiveIntegerField(default=0)),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True, max_length=255, upload_to="public/courses/%Y/%m/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_offerings",
                        to="bots.bot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "course_offering",
                "ordering": ("sort_order", "id"),
                "indexes": [
                    models.Index(
                        fields=["bot", "is_active"], name="course_bot_active_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["bot", "is_active"], name="property_bot_active_idx"
            ),
        ),
    ]
