# Generated by Django 5.2.17 on 2026-08-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
