# Generated by Django 5.1.15 on 2026-08-10 11:14

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityLinkNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_nonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_link_nonce',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('default_locale', models.CharField(default='en', max_length=8)),
                ('default_currency', apps.core.models.CurrencyCodeField(default='USD', max_length=8)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChannelIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale')], max_length=16)),
                ('platform_user_id', models.CharField(max_length=64)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_identity',
                'constraints': [models.UniqueConstraint(fields=('platform', 'platform_user_id'), name='channel_identity_uniq')],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=16)),
                ('extra_permissions', models.JSONField(blank=True, default=list, help_text='Additional scopes granted beyond the role.')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='customers.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_membership',
                'indexes': [models.Index(fields=['user', 'tenant'], name='membership_user_tenant_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='tenant_membership_uniq')],
            },
        ),
    ]
