# Generated by Django 5.1.15 on 2026-08-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('field', models.CharField(max_length=64)),
                ('locale', models.CharField(max_length=8)),
                ('value', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'translation',
                'indexes': [models.Index(fields=['content_type', 'object_id', 'locale'], name='translation_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'field', 'locale'), name='translation_unique')],
            },
        ),
    ]
