# Generated by Django 5.2.17 on 2026-08-11 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0001_initial"),
        ("orders", "0004_order_provisioning_strategy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisioningJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("strategy", models.CharField(max_length=24)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("AWAITING_CUSTOMER", "Waiting for the customer"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("COMPENSATING", "Compensating"),
                            ("COMPENSATED", "Compensated"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=24,
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=0)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_detail", models.TextField(blank=True)),
                (
                    "bot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="bots.bot",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_jobs",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "provisioning_job",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProvisioningStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_slug", models.CharField(max_length=64)),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked on the customer"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=0)),
                ("input", models.JSONField(blank=True, default=dict)),
                ("output", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="provisioning.provisioningjob",
                    ),
                ),
            ],
            options={
                "db_table": "provisioning_step",
                "ordering": ("sequence",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "step_slug"), name="provisioning_step_uniq"
                    )
                ],
            },
        ),
    ]
