# Generated by Django 5.2.17 on 2026-08-10 23:32

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_order_orderevent_orderitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MANUAL_CARD", "Manual card transfer"),
                            ("MANUAL_CRYPTO", "Manual cryptocurrency transfer"),
                            ("GATEWAY", "Automated gateway"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "provider_slug",
                    models.SlugField(
                        help_text="Which provider implementation handles this method.",
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("currency", apps.core.models.CurrencyCodeField(max_length=8)),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        help_text="TRC20, ERC20, Bitcoin… for crypto methods.",
                        max_length=32,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("instructions", models.TextField(blank=True)),
                ("minimum_amount_minor", models.BigIntegerField(default=0)),
                (
                    "country_scope",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ISO country codes. Empty means anywhere.",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "db_table": "payment_method",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("currency", apps.core.models.CurrencyCodeField(max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Awaiting payment"),
                            ("RECEIPT_SUBMITTED", "Receipt submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("tx_hash", models.CharField(blank=True, default="", max_length=128)),
                ("sender_wallet", models.CharField(blank=True, max_length=128)),
                ("network", models.CharField(blank=True, max_length=32)),
                ("payer_note", models.CharField(blank=True, max_length=255)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                (
                    "internal_note",
                    models.TextField(
                        blank=True, help_text="Staff only. Never shown to the customer."
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="payments.paymentmethod",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(max_length=255, upload_to="receipts/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveIntegerField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Not scanned"),
                            ("CLEAN", "Clean"),
                            ("INFECTED", "Infected"),
                            ("ERROR", "Scan failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("uploaded_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="payments.payment",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_receipt",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="payment_status_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tx_hash", ""), _negated=True),
                fields=("tx_hash",),
                name="payment_tx_hash_globally_unique",
            ),
        ),
    ]
