# Generated by Django 5.2.17 on 2026-08-10 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "db_table": "business_template",
                "ordering": ("sort_order", "slug"),
            },
        ),
        migrations.CreateModel(
            name="TemplateFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Pre-selected in the builder; the customer may remove it.",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Cannot be removed — the template is meaningless without it.",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_features",
                        to="features.feature",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_features",
                        to="business_templates.businesstemplate",
                    ),
                ),
            ],
            options={
                "db_table": "template_feature",
                "ordering": ("sort_order",),
            },
        ),
        migrations.AddField(
            model_name="businesstemplate",
            name="features",
            field=models.ManyToManyField(
                related_name="templates",
                through="business_templates.TemplateFeature",
                to="features.feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatefeature",
            constraint=models.UniqueConstraint(
                fields=("template", "feature"), name="template_feature_uniq"
            ),
        ),
    ]
