# Generated by Django 5.2.17 on 2026-08-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="working_hours_text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
