# Generated by Django 5.2.17 on 2026-08-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_businessprofile_working_hours_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessprofile",
            name="logo_file_key",
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="logo",
            field=models.FileField(blank=True, upload_to="public/logos/%Y/%m/"),
        ),
    ]
